steps: 
  # - name: alpine
  #   args: ['sh', 'echo test && ls -l && echo test 2']
  # - name: alpine
  #   args: ['ls', '-l' , '&&' , 'echo test']
  - name: alpine
    args: ['ls', '-l'] 
  # - name: 'circleci/openjdk:8u171-jdk'
  #   args: ['bash', './gradlew' ,'clean','build', '-x', ':neo4j-store:test']
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean','build', '-x', ':neo4j-store:test']
    env:
    - 'BUILD_ENV=CI_CD'
  - name: 'docker/compose:1.15.0'
    args: ['up', '--build', '--abort-on-container-exit']  

options:
 machineType: 'N1_HIGHCPU_32'