steps: 
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean','build', '-x', ':neo4j-store:test']
    env:
    - 'BUILD_ENV=CI_CD'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/pi-ostelco-dev/prime:$SHORT_SHA', '.']
    dir: 'prime'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/pi-ostelco-dev/pseudonym-server:$SHORT_SHA', '.']
    dir: 'pseudonym-server'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/pi-ostelco-dev/ocsgw:$SHORT_SHA', '.']    
    dir: 'ocsgw'

  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://pantel-prod-temporary/pantel-prod.json', 'pantel-prod.json']  

  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://pi-ostelco-dev-k8s-key-store/keys/dev_cluster_client_certificate.crt', 'prime/client_certificate.crt']  
    
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://pi-ostelco-dev-k8s-key-store/keys/dev_cluster_cluster_ca.crt', 'prime/cluster_ca.crt'] 
    
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://pi-ostelco-dev-k8s-key-store/keys/dev_cluster_client_key.key', 'prime/client_key.key']   
  
  - name: 'praqma/helmsman:test-1.4.0'
    secretEnv: ['PI_DEV_K8S_PASSWORD', 'PI_DEV_K8S_ENDPOINT']
    entrypoint: 'sh'
    args:
    - '-c'
    - | 
        FIRBASE_SERVICE_ACCOUNT=$(cat pantel-prod.json | base64 )
        cd prime
        sed -i "s/PANTEL_PROD/$${FIRBASE_SERVICE_ACCOUNT}/g" prime-dev-values.yaml
        export TAG=$SHORT_SHA
        helmsman --debug --apply -f helmsman-dev-deployment.toml  

    
images: ['eu.gcr.io/pi-ostelco-dev/prime:$SHORT_SHA','eu.gcr.io/pi-ostelco-dev/pseudonym-server:$SHORT_SHA' , 'eu.gcr.io/pi-ostelco-dev/ocsgw:$SHORT_SHA']
options:
 machineType: 'N1_HIGHCPU_32'

secrets:
- kmsKeyName: projects/pi-ostelco-dev/locations/global/keyRings/pnatel-prod-key/cryptoKeys/k8s-password-key
  secretEnv:
    PI_DEV_K8S_PASSWORD: CiQAPK2R5KzrDwVC+VJiOiVlGZvbxaouESlYdJ3pYNS+mBqik4ASOQD5PlVZqnnwi9n4o4rlie6+DiuCCFZfcYQlPYep7uQaJSy0hfGysNrQ3jHSIo6dLYljuB6NizXghA==
- kmsKeyName: projects/pi-ostelco-dev/locations/global/keyRings/pnatel-prod-key/cryptoKeys/pantel-prod-kms-key
  secretEnv:
    PI_DEV_K8S_ENDPOINT: CiQA7nht2F7EjdFpAOZANpG1rCBGNH24C294P3VLgyQ30vDrPTsSPwBphHK8sc+PbTAzX+IWyvFm6bylXVbP1QLE+iQx4qyVxFd6y+Wfw/9BxzY7BxpDQJRGuYaD8oFs05I+jGy53A==    