# metadata -- add as many key/value pairs as you want
[metadata]
maintainer = "Sami Alajrami (sami@praqma.com)"
description = "Desired state file for deploying Prime and its components."

# paths to the certificate for connecting to the cluster
# you have to use exact key names here : 'caCrt' for certificate and 'caKey' for the key and caClient for the client certificate
[certificates]
caClient = "client_certificate.crt" 
caCrt = "cluster_ca.crt" 
caKey = "client_key.key" 

[settings]
kubeContext = "ostelco" # will try connect to this context first, if it does not exist, it will be created using the details below
username = "admin"
password = "$PI_DEV_K8S_PASSWORD" # the name of an environment variable containing the k8s password
clusterURI = "$PI_DEV_K8S_ENDPOINT" # the name of an environment variable containing the cluster API
serviceAccount = "tiller" # k8s serviceaccount. If it does not exist, it will be created.
storageBackend = "secret" # default is configMap
#slackWebhook = "$slack" # or "your slack webhook url"

# define your environments and their k8s namespaces
# syntax: 
# [namespaces.<your namespace>] -- whitespace before this entry does not matter, use whatever indentation style you like 
 # protected = <true or false> -- default to false 
[namespaces]
  [namespaces.kube-system]
  installTiller = false
  [namespaces.dev]
   installTiller = true
   tillerServiceAccount = "tiller-dev" 


# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
# private repos hosted in s3,GCS buckets are supported
[helmRepos]
ostelco="https://storage.googleapis.com/pi-ostelco-helm-charts-repo/"




[apps]
    [apps.prime]
    name = "prime"
    description = "Prime Dev deployment"
    namespace = "dev"
    enabled = true
    chart = "ostelco/prime"
    version = "0.2.1"
    valuesFile = "prime-dev-values.yaml"
    [apps.prime.set]
    "prime.tag"="\"$TAG\"" # double quotes are needed to avoid helm converting git SHA into scientific numbers format 
    "firebaseServiceAccount"="$PANTEL_SECRETS_FILE"